apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    https://dex.auth.svc.cluster.local:5556/dex
    issuer: https://kf.ds.bloomboard.com/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
---
test: 123
anothertest: 382323
yetanother: 2938
---
test: 456