version: '3.1'

services:
  basic_mlpipeline_jupyternotebook:
    image: jupyter/minimal-notebook/mlpipeline:ubuntu-22.04
    build: .
    container_name: mlpipeline_jupyternotebook_container
    working_dir: /home/jovyan/work
    #environment:
    #  - PASSWORD=password
    # command:
    ports: 
      - 8888:8888
    volumes:
      - type: bind
        source: ./volumebindmount
        target: /home/jovyan/work
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true