# syntax = docker/dockerfile:1.3-labs
ARG BASE_CONTAINER=haskell:slim-buster

FROM $BASE_CONTAINER

LABEL author="Patrick Delaney"

COPY volumebindmount /home/volumebindmount

# install nano
# install cabal
# add to bashrc