version: '3.1'

services:
  playwithgolang_service:
    image: golang-bullseye:latest
    build: .
    container_name: playwithgolang_container
    working_dir: /home/
    # command:
    # ports: 
    #  - 1313:1313
    volumes:
      - type: bind
        source: ./volumebindmount
        target: /home/volumebindmount
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true