apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/manifests/common/dex/overlays/istio/?ref=v1.5.0

patchesStrategicMerge:
- config-map.yaml

namespace: auth
