version: '3.1'

services:
  python3p8_jupyternotebook:
    image: jupyter/scipy-notebook:python-3.8-with-deps
    build: .
    container_name: python3p8_jupyternotebook_container
    working_dir: /home/jovyan/work
    environment:
    - PASSWORD=password
    # command:
    ports: 
      - 8888:8888
    volumes:
      - type: bind
        source: ./volumebindmount
        target: /home/jovyan/work
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true