#!/bin/bash

# install package manager and update with hex and rebar
./hexrebar.sh

# setup a new app
./newapp.sh

# update dependencies
./update.sh

# compile the application
./compile.sh

# run the application
./runnohalt.sh
